# SPDX-License-Identifier: CC0-1.0
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6

    working_directory: ~/repo
    steps:
      - checkout
      - run: make
      - run: make check
